FROM python:3.10

#Crear un directorio de trabajo
WORKDIR /servidor2
COPY servidor2.py .

#descarga flask
RUN pip install flask

#ejecuto la aplicación
CMD [ "python", "servidor2.py" ]
#Exponer el puerto
EXPOSE 5000