FROM python:3.10

#Crear un directorio de trabajo
WORKDIR /servidor1
COPY servidor1.py .

#descarga flask
RUN pip install flask

#ejecuto la aplicación
CMD [ "python", "servidor1.py" ]

#Exponer el puerto
EXPOSE 5000