FROM python:3.10

#Crear un directorio de trabajo
WORKDIR /servidor3
COPY servidor3.py .

#descarga flask
RUN pip install flask

#ejecuto la aplicación
CMD [ "python", "servidor3.py" ]

#Exponer el puerto
EXPOSE 5000