FROM python:3.10

#Crear un directorio de trabajo
WORKDIR /servidor4
COPY servidor4.py .

#descarga flask
RUN pip install flask

#ejecuto la aplicación
CMD [ "python", "servidor4.py" ]

#Exponer el puerto
EXPOSE 5000